service: poc-custom-authorizer
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  authorization:
    handler: src/handlers/auth.hasAuthorized

  auth:
    handler: src/handlers/auth.authenticate
    events:
      - http:
          path: /auth/login
          method: post
          

  todo_getAll:
    handler: src/handlers/todo.getAll
    events:
      - http:
          path: /todos
          method: get
          authorizer: authorization

  todo_getById:
    handler: src/handlers/todo.getById
    events:
      - http:
          path: /todos/{id}
          method: get
          authorizer: authorization
